### ISSUE TITLE
Feature Request: GPU functions inside a GPU table

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#134]
Many of the GPU functions have generic names like triangle, rect, color, etc. that you can easily overwrite  on accident by declaring a local variable or defining an argument with the same name. I suggest to place all GPU functions in a GPU table so that executing them would require first calling the GPU- eg:
```
GPU.line(0,0,10,-2)
GPU.color(7)
```
etc.

**Comment by LoganDark** [comment]
Or just place (a copy of) _all_ of the API functions inside a global "LIKO" table, and keep the existing functions without the `LIKO.` prefix for compatibility reasons.

**Comment by Rami-Sabbagh** [comment]
That's why I added LIKO-12 functions highlighting in the code editor, so people don't override them by a mistake.

And to help solve this issue, I will add a copy of GPU functions in `GPU` table (So you can use both).

The functionality exists, just a little change in run.lua and boot.lua and everything will be fine.

**Comment by ghost** [comment]
Awesome! :grinning:

**Comment by LoganDark** [comment]
@RamiLego4Game I suggested putting (a copy of, instead of moving) all API functions in a global `LIKO` table, instead of just the GPU functions. What's your opinion on that?

**Comment by Rami-Sabbagh** [comment]
This problem had been fixed in the new BIOS rewrite
