### ISSUE TITLE
Installation guide (Linux)

### ISSUE THREAD

**Issue by Gapstare** [LIKO-12/LIKO-12#186]
I have a couple of computers with a Ubuntu-based distro on them called Trisquel.

`sudo apt install love=0.10.2ppa1` does not work for me, but `sudo apt install love` does and gives me a version called 11.1ppa1 (strange version numbering there? :) ).

The ppa seems to be 64-bit only too but I don't know if it's worth mentioning since the number of 32-bit machines in actual use is getting smaller every day.

**Comment by Rami-Sabbagh** [comment]
Hello, Thanks for taking your time and reporting this.

I've forgot to update the installation instructions for Linux, sorry,

LIKO-12 starting from the V0.8.0_PRE release is now using LÖVE 11.1, it also turns out that the PPA removes the old versions of love which is bad, but now LÖVE supports AppImages, So I'm going to use them for future linux builds, Maybe I'll upload a new linux build for 0.8.0.

LIKO-12 is written in Lua, and so it works for both 32-bit and 64-bit, if love PPA doesn't have the 32-bit version, you can download an AppImage of it from http://love2d.org

**Comment by Rami-Sabbagh** [comment]
I'll close the issue for now, if you still have problems please re-open this issue

**Comment by Gapstare** [comment]
Thank you for your reply and for the tip about AppImage, that installation method is new to me.

And keep up the good work, Liko-12 is great fun! :-)
