### ISSUE TITLE
Impossible to use Third Party Libraries

### ISSUE THREAD

**Issue by OniriCorpe** [LIKO-12/LIKO-12#221]
**Describe the bug**
I cannot use any Third Party Libraries in LIKO-12 1.0.0 version.

**To Reproduce**
1. Go to the code editor
2. Type `local world = bump.newWorld(50)` (as seen as exemple for 'Bump' library, in the old documentation for 0.6 version) in your code (or another function from TPL provided in LIKO-12)
3. Execute your code
4. Error: `attempt to index global 'bump' (a nil value)`

**Expected behavior**
We should be able to use any of the TPL provided in LIKO-12.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 64.0

**Comment by Rami-Sabbagh** [comment]
That's because I've changed the way that third-party libraries are provided.
Instead of all of them having a single instance and being provided as a global, you can now load them by calling the `Library` function:
```lua
local bump = Library("bump")
local world = bump.newWorld(50)
```
You can check the available libraries and their names in this file:
https://github.com/LIKO-12/LIKO-12/blob/master/OS/DiskOS/Runtime/Globals/05_Libraries.lua

If you found out about third-party libraries from the demos in an older version, then you maybe have to re-install them by running `install_demos` again.
