### ISSUE TITLE
Html 5 export?

### ISSUE THREAD

**Issue by girobusan** [LIKO-12/LIKO-12#58]
Do you plan to implement this? This one is a strong "selling point" for Pico. #discussion

**Comment by feserr** [comment]
LIKO-12 uses Love2D and it do not support it officially but there are some people that have try it. Here is someone that have do it: [love-webplayer](https://github.com/ghoulsblade/love-webplayer)

**Comment by girobusan** [comment]
Last activity – 4 years ago. Looks like a dead project.

**Comment by buckle2000** [comment]
@girobusan FYI: https://github.com/TannerRogalsky/love.js/

**Comment by ahungry** [comment]
Wow that's pretty great, the mari0 running on the port worked fairly well.

**Comment by pablomayobre** [comment]
I'm working on this, but it will probably require some hard work! Expect news soon

**Comment by egordorichev** [comment]
Any news, @Positive07?

**Comment by pablomayobre** [comment]
No, sorry. I have been busy with other stuff.

I gathered some info though (mostly the same @RamiLego4Game provided), love.js only works on Chrome Canary and Firefox Nightly since it uses pthreads which are not broadly implemented yet.

There were some problems with the Shaders (but that may have been fixed in df0b7f22e3b65b399f425011b2396503aeab8103)

Some changes are needed regarding screen size (they should be statically specified in `conf.lua`, currently LIKO12 starts without a window, and it creates one later on in the `load` phase)

We need a good [BitOps](http://bitop.luajit.org/)-like library since BitOps is not included in bare Lua 5.1 (this is the one used in love.js since LuaJIT cannot be compiled into asm.js)

And that is basically it... love.js has some problems on Windows (like [this one](https://github.com/TannerRogalsky/love.js/issues/53#issuecomment-312979230)) which have slowed me down, and I need to install one of the browsers I said before because mine didn't work back when I tried.

**Comment by tarkadaal** [comment]
Is this still in progress? Are there any specific things that I (or others) can do to help?

**Comment by Rami-Sabbagh** [comment]
This is not under work, It's waiting until LIKO-12 itself get stable and
complete, so I could handle rewriting the engine in javascript.

**Comment by Rami-Sabbagh** [comment]
It has been decided that html5 support won't ever exist, because maintaining 2 versions of the engine (LÖVE and HTML5) will be difficult.
