### ISSUE TITLE
Folder command?

### ISSUE THREAD

**Issue by mseyne** [LIKO-12/LIKO-12#61]
When I use the command folder, liko12 freeze.

Is it a shortcut to open the folder in windows ?
\AppData\Roaming\LOVE\liko12\data

**Comment by Rami-Sabbagh** [comment]
Strange issue, it's caused by the löve framework. What I do is ask love about the appdata folder path, join it with the current directory in liko12 terminal, then open it by openning the url "file://" + finalPath

could you provide some extra info about your platform (os, cpu, gpu, etc..), I will be available to help you at sunday

**Comment by Rami-Sabbagh** [comment]
yes, it's a shortcut, you can do it manually, it's for lazy people who don't know how to find the appdata folder.

**Comment by mseyne** [comment]
Thank you for your answer, I have found the problem, it is me. My graphic card bug a lot lately and will die soon I am sure. I deactivated my graphic card and it work fine.
